#!/usr/bin/env bash
# Copy file between servers
if [ $# -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no $1 $3@$2:~/ -i $4
fi
