#!/usr/bin/env bash
# Copy file between servers
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $4 -eq 4 ]
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
