#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project and 
# you should be familiar with it. Today we will make up a story based on it
file="/etc/passwd"
while IFS=":" read -r line
do
	set -- "$line"
        echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
done < "$file"
