#!/usr/bin/env bash
# Displays numbers from 1 to 20
lim=1
while [ $lim -le 20 ]
do
	echo $lim
	case $lim in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((lim++))
done
